# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Student' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Student
pod 'SwiftyJSON'
pod 'Alamofire'
pod 'ImagePicker'
pod 'TransitionButton', '0.5.1'
pod 'Firebase/Database'
pod 'Firebase/Messaging'
pod 'Firebase'
pod 'Firebase/Storage'
pod 'TensorFlow-experimental'
end
